//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public int user_id { get; set; }
        public int author_id { get; set; }
        public int rating { get; set; }
        public System.DateTime date_added { get; set; }
        public string title { get; set; }
        public string text { get; set; }
    }
}
