//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marketplaceEntities : DbContext
    {
        public marketplaceEntities()
            : base("name=marketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ad> ad { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<observed_ad> observed_ad { get; set; }
        public virtual DbSet<reported_post> reported_post { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<chat> chat { get; set; }
    }
}
