//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketplaceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int message_id { get; set; }
        public int chat_id { get; set; }
        public int author_id { get; set; }
        public string message_text { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
